language: node_js
node_js:
  - "node"
before_install:
  - export PATH=$PATH:`yarn global bin`
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script:
  - yarn start
  - greenkeeper-lockfile-upload
